import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import { bunny } from 'laravel-vite-plugin/fonts';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/js/utils/api.js',
                'resources/css/components/design-system.css',
                'resources/css/components/sidebar.css',
                'resources/css/components/header.css',
                'resources/css/auth/login.css',
                'resources/css/auth/register.css',
                'resources/css/auth/forgot-password.css',
                'resources/css/auth/reset-password.css',
                'resources/css/auth/landing.css',
                'resources/js/auth/login.js',
                'resources/js/auth/register.js',
                'resources/js/auth/forgot-password.js',
                'resources/js/auth/reset-password.js',
                'resources/js/auth/landing.js',
                'resources/css/user/dashboard.css',
                'resources/css/user/my-events.css',
                'resources/css/user/certificates.css',
                'resources/css/user/notifications.css',
                'resources/css/user/profile.css',
                'resources/css/user/events.css',
                'resources/css/user/event-detail.css',
                'resources/css/user/settings.css',
                'resources/css/admin/admin-shared.css',
                'resources/css/admin/dashboard.css',
                'resources/css/admin/events.css',
                'resources/css/admin/create-event.css',
                'resources/css/admin/edit-event.css',
                'resources/css/admin/participants.css',
                'resources/css/admin/attendance.css',
                'resources/css/admin/certificates.css',
                'resources/css/admin/messages.css',
                'resources/css/admin/announcements.css',
                'resources/css/admin/students.css',
                'resources/css/admin/notifications.css',
                'resources/css/admin/settings.css',
                'resources/js/components/sidebar.js',
                'resources/js/components/header.js',
                'resources/js/user/dashboard.js',
                'resources/js/user/my-events.js',
                'resources/js/user/certificates.js',
                'resources/js/user/notifications.js',
                'resources/js/user/profile.js',
                'resources/js/user/events.js',
                'resources/js/user/event-detail.js',
                'resources/js/user/settings.js',
                'resources/js/admin/admin-shared.js',
                'resources/js/admin/dashboard.js',
                'resources/js/admin/events.js',
                'resources/js/admin/create-event.js',
                'resources/js/admin/edit-event.js',
                'resources/js/admin/participants.js',
                'resources/js/admin/attendance.js',
                'resources/js/admin/certificates.js',
                'resources/js/admin/messages.js',
                'resources/js/admin/announcements.js',
                'resources/js/admin/students.js',
                'resources/js/admin/notifications.js',
                'resources/js/admin/settings.js',
            ],
            refresh: true,
            fonts: [
                bunny('Instrument Sans', {
                    weights: [400, 500, 600],
                }),
            ],
        }),
        tailwindcss(),
    ],
    server: {
        host: '127.0.0.1',
        port: 5173,
        strictPort: false,
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
